AWSTemplateFormatVersion: '2010-09-09'
Description: 'Deploy WordPress with MySQL'

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: 'EC2 KeyPair Name'
  DBName:
    Type: String
    Default: wordpressdb
    Description: 'Database Name'
  DBUser:
    Type: String
    Default: wpadmin
    Description: 'Database Username'
  DBPassword:
    Type: String
    NoEcho: true
    Description: 'Database Password'
  DBRootPassword:
    Type: String
    NoEcho: true
    Description: 'MySQL Root Password'

Resources:
  WordPressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP, SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WordPressDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      BackupRetentionPeriod: 7
      PubliclyAccessible: true

  WordPressInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref WordPressSecurityGroup
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 in us-east-1
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
          yum install -y httpd mariadb-server
          systemctl start httpd
          systemctl enable httpd
          cd /var/www/html
          wget https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          cp -r wordpress/* .
          rm -rf wordpress latest.tar.gz
          chown -R apache:apache /var/www/html
          systemctl restart httpd

Outputs:
  WebsiteURL:
    Description: "WordPress website URL"
    Value: !Sub "http://${WordPressInstance.PublicDnsName}/"
